# Generated by Django 5.2.2 on 2025-07-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_ratings_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
